apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: aifti-teams-alerts
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
    namespace: flux-system
  - kind: Kustomization
    name: '*'
    namespace: flux-system
  - kind: HelmRelease
    name: '*'
    namespace: flux-system
  - kind: GitRepository
    name: '*'
    namespace: monitoring
  - kind: Kustomization
    name: '*'
    namespace: monitoring
  - kind: HelmRelease
    name: '*'
    namespace: monitoring
  - kind: GitRepository
    name: '*'
    namespace: prefect
  - kind: Kustomization
    name: '*'
    namespace: prefect
  - kind: HelmRelease
    name: '*'
    namespace: prefect
  - kind: GitRepository
    name: '*'
    namespace: splunk-o11y-suite
  - kind: Kustomization
    name: '*'
    namespace: splunk-o11y-suite
  - kind: HelmRelease
    name: '*'
    namespace: splunk-o11y-suite
  providerRef:
    name: aifti-teams
