apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/dev/dev-cluster-1/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-cluster-1
    namespace: flux-system
