load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_library")

jsonnet_library(
    name = "custom_app",
    srcs = ["custom-app.libsonnet"],
    visibility = ["//clusters:__subpackages__"],
)
