name: rebuild-manifests
on:
  push:
    branches-ignore:
      - validated
jobs:
  rebuild-manifests:
    name: Rebuild and validate manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup-jsonnet
        uses: zendesk/setup-jsonnet@v10
        with:
          version: v0.18.0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6" # The Go version to download (if necessary) and use.
      - name: Cache vendored libraries
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-${{ hashFiles('jsonnetfile.lock.json') }}
      - name: Install dependencies
        run: |
          jb install
          go install github.com/brancz/gojsontoyaml@latest
      - name: Regenerate and validate manifests
        run: |
          scripts/build.sh
          scripts/check-dirty.sh
      - name: Push to release branch
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "TODO: Push changes to 'validated' branch."
